Starting GS2 runs
Traceback (most recent call last):
  File "/marconi_scratch/userexternal/rjorge00/some_optimizations/GS2_SIMSOPT_ITG/./test_parameters.py", line 251, in <module>
    start_time = time();growth_rate, sum_gamma_o_ky=run_gs2(nphi, nperiod, nlambda, nstep, dt, negrid, ngauss)
  File "/marconi_scratch/userexternal/rjorge00/some_optimizations/GS2_SIMSOPT_ITG/./test_parameters.py", line 238, in run_gs2
    eigenPlot(output_file)
  File "/marconi_scratch/userexternal/rjorge00/some_optimizations/GS2_SIMSOPT_ITG/./test_parameters.py", line 97, in eigenPlot
    f = netCDF4.Dataset(stellFile,'r',mmap=False)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/marconi_scratch/userexternal/rjorge00/some_optimizations/GS2_SIMSOPT_ITG/test_out_nfp4_QH_initial_ln1.0_lt3.0/gs2Input_nphi141_nperiod5.0_nlambda33negrid9ngauss3_nstep330_dt0.4_kymin0.3_kymax3.0_nky8_ln1.0_lt3.0.out.nc'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[29622,1],0]
  Exit code:    1
--------------------------------------------------------------------------
