Traceback (most recent call last):
  File "./test_final.py", line 63, in <module>
    vmec = Vmec(vmec_file)
  File "/m100/home/userexternal/rjorge00/simsopt/src/simsopt/mhd/vmec.py", line 370, in __init__
    self._boundary = SurfaceRZFourier.from_wout(filename, nphi=nphi, ntheta=ntheta)
  File "/m100/home/userexternal/rjorge00/simsopt/src/simsopt/geo/surfacerzfourier.py", line 154, in from_wout
    f = netcdf_file(filename, mmap=False)
  File "/m100/home/userexternal/rjorge00/.conda/envs/simsopt/lib/python3.8/site-packages/scipy/io/_netcdf.py", line 245, in __init__
    self.fp = open(self.filename, '%sb' % omode)
FileNotFoundError: [Errno 2] No such file or directory: '/m100/home/userexternal/rjorge00/some_optimizations/GS2_SIMSOPT_ITG/output_MAXITER350_least_squares_nfp2_QA_QA/wout_final.nc'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[60590,1],0]
  Exit code:    1
--------------------------------------------------------------------------
